"""Install a temporary visual probe; it is never part of a distributed build."""
import json
from pathlib import Path

source = Path("src/main/java/com/simibubi/create/infrastructure/gui/MenuRenderProbe.java")
source.write_text("package com.simibubi.create.infrastructure.gui;\n\nimport java.nio.file.Files;\nimport java.nio.file.Path;\nimport com.mojang.blaze3d.platform.NativeImage;\nimport net.fabricmc.api.ClientModInitializer;\nimport net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;\nimport net.minecraft.client.Screenshot;\nimport net.minecraft.client.gui.screens.TitleScreen;\n\npublic class MenuRenderProbe implements ClientModInitializer {\n\tprivate int stage = -1;\n\tprivate long changed;\n\tprivate final String[] modes = {\"title\", \"modmenu\"};\n\t@Override\n\tpublic void onInitializeClient() {\n\t\tClientTickEvents.END_CLIENT_TICK.register(mc -> {\n\t\t\tif (mc.getOverlay() != null) return;\n\t\t\tlong now = System.currentTimeMillis();\n\t\t\tif (stage == -1) {\n\t\t\t\tstage = 0;\n\t\t\t\tmc.setScreen(new CreateMainMenuScreen(stage == 0 ? new TitleScreen() : new com.terraformersmc.modmenu.gui.ModsScreen(new TitleScreen())));\n\t\t\t\tchanged = now;\n\t\t\t\treturn;\n\t\t\t}\n\t\t\tif (now - changed < 5000) return;\n\t\t\ttry {\n\t\t\t\tPath dir = Path.of(\"../build/menu-smoke\");\n\t\t\t\tFiles.createDirectories(dir);\n\t\t\t\ttry (NativeImage image = Screenshot.takeScreenshot(mc.getMainRenderTarget())) {\n\t\t\t\t\timage.writeToFile(dir.resolve(modes[stage] + \".png\"));\n\t\t\t\t}\n\t\t\t\tSystem.out.println(\"MENU_PROBE captured \" + modes[stage]);\n\t\t\t} catch (Exception e) {\n\t\t\t\tthrow new RuntimeException(e);\n\t\t\t}\n\t\t\tif (++stage == modes.length) {\n\t\t\t\tmc.stop();\n\t\t\t\treturn;\n\t\t\t}\n\t\t\tmc.setScreen(new CreateMainMenuScreen(new com.terraformersmc.modmenu.gui.ModsScreen(new TitleScreen())));\n\t\t\tchanged = now;\n\t\t});\n\t}\n}\n")
manifest = Path("src/main/resources/fabric.mod.json")
value = json.loads(manifest.read_text())
value["entrypoints"]["client"].append("com.simibubi.create.infrastructure.gui.MenuRenderProbe")
manifest.write_text(json.dumps(value, indent=2))
